services:
  - type: web
    name: satltis-scraping
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-patient-cell-ahrb8zvy-pooler.c-3.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_zhybVqrFSt30
      - key: DB_SSLMODE
        value: require

