services:
  - type: web
    name: satltis-scraping
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: satltis-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: satltis-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: satltis-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: satltis-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: satltis-db
          property: password

databases:
  - name: satltis-db
    databaseName: satltis
    user: satltis_user
    plan: free

